pipeline:
  general:
    verbose: true
    debug: true
    show_plots: false

  input:
    start: "2016-12-21T00:30:00"
    end: "2016-12-21T00:45:00"
    timezone: "America/Los_Angeles"
  
  search:
    export_template: "data/encounters/{filename}-{timeframe}.csv"
    filename: "monterey_bay_50km"
    geometery_file_path_template: "data/geo/{filename}.geojson"
    species: "humpback_whale"
    columns:
      - "id"
      - "latitude"
      - "longitude"
      - "startDate"
      - "startTime"
      - "endTime"
      - "timezone"
      - "displayImgUrl"

  audio:
    url_template: "https://pacific-sound-16khz.s3.amazonaws.com/{year}/{month:02}/{filename}"
    filename_template: "MARS-{year}{month:02}{day:02}T000000Z-16kHz.wav"
    source_sample_rate: 16000
    margin: 30 # TODO set to 900  # seconds  
    offset: 13 # TODO set to 0    # hours
    output_path_template: "data/audio/raw/{year}/{month:02}/{filename}"
    skip_existing: false # if true, skip downstream processing of existing audio files (false during development)

  sift:
    output_path_template: "data/audio/{sift}/{year}/{month:02}/{filename}"
    max_duration: 600  # seconds
    plot: true
    show_plot: false
    plot_path_template: "data/plots/{sift}/{year}/{month:02}/{day:02}/{plot_name}.png"
    window_size: 512

    # Specific sift-mechanism parameters
    butterworth:
      highcut: 1500
      lowcut: 50
      order: 5
      output: "sos"  # "sos" or "ba" 
      sift_threshold: 0.015

  classify:
    backend: "tensorflow"
    hydrophone_sensitivity: -168.8
    batch_duration:  600  # seconds
    model_sample_rate: 10000
    plot_scores: true
    plot_path_template: "data/plots/results/{year}/{month:02}/{plot_name}.png"
    url: https://tfhub.dev/google/humpback_whale/1
    model_url: "http://127.0.0.1:5000/predict"
    med_filter_size: 3

  postprocess:
    min_gap: 60  # 1 minute
    pooling: "average"
    confidence_threshold: 0.5
    output_path_template: "data/labels/{year}/{month:02}/{day:02}.csv"

  


