pipeline:
  general:
    verbose: true
    debug: true
    show_plots: false
  
  search:
    export_template: "data/encounters/{filename}-{timeframe}.csv"
    filename: "monterey_bay_50km"
    geometery_file_path_template: "data/geo/{filename}.geojson"

  audio:
    output_path_template: "data/audio/raw/{year}/{month:02}/{filename}"
    skip_existing: false # if true, skip downstream processing of existing audio files (false during development)

  sift:
    output_path_template: "data/audio/{sift}/{year}/{month:02}/{filename}"
    max_duration: 600  # seconds
    plot: true
    show_plot: false
    plot_path_template: "data/plots/{sift}/{year}/{month:02}/{day:02}/{plot_name}.png"
    window_size: 512

  classify:
    batch_duration:  600  # seconds
    inference_retries: 3
    plot_scores: true
    plot_path_template: "data/plots/results/{year}/{month:02}/{plot_name}.png"

  postprocess:
    min_gap: 60  # 1 minute
    pooling: "average"
    confidence_threshold: 0.5
    output_path_template: "data/labels/{year}/{month:02}/{day:02}.csv"
