pipeline:
  general:
    verbose: true
    debug: true
    show_plots: false
    is_local: true
  

  audio:
    skip_existing: false # if true, skip downstream processing of existing audio files (false during development)

  sift:
    max_duration: 600  # seconds
    plot: true
    show_plot: false
    window_size: 512

  classify:
    batch_duration:  600  # seconds
    inference_retries: 3
    plot_scores: true
    plot_pat_template: "data/plots/results/{year}/{month:02}/{plot_name}.png"

  postprocess:
    min_gap: 60  # 1 minute
    confidence_threshold: 0.5
