name: Publish Latest Images to Docker Hub

on:
  push:
    branches:
      - main  # Runs on push to the main branch


env:
  MODEL_REGISTERY: ${{ secrets.MODEL_REGISTERY }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  publish-model-server:
    name: Publish Latest Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Auth (Docker Hub)
        id: docker-auth-dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{env.DOCKERHUB_TOKEN}}

      - name: Publish Latest Model Server Image
        run: make publish-latest-model-server
        env:
          MODEL_REGISTERY: ${{ env.MODEL_REGISTERY }}
          PUBLIC_MODEL_REGISTERY: docker.io/${{ env.DOCKERHUB_USERNAME }}

      - name: Publish Latest Pipeline Worker Image
        run: make publish-latest-pipeline-worker
        env:
          MODEL_REGISTERY: ${{ env.MODEL_REGISTERY }}
          PUBLIC_MODEL_REGISTERY: docker.io/${{ env.DOCKERHUB_USERNAME }}
